### ISSUE TITLE
invisible files/folders in additions directory

### ISSUE THREAD

**Issue by tonytee** [OnionIoT/openwrt-imagebuilder-wrapper#17]
Hi,

I'm making my first steps with your imagebuilder, trying to get my old provisioning system transferred to this new method.
I encounter this problem.

Docs state "Everything from the additions/ directory will be copied into the image builder directory before build."
However, this seems to be not true for the .invisible .folders

This is a problem for me because i need to place:
.gitignore
.local
.ssh (with my keys in it)

do you know of a workaround? or should this maybe be working?

thanks, tony

**Comment by tonytee** [comment]
Hmmm...

i'm afraid i have to dismiss this myself as being utter bogus...
they are actually there... maybe i did a wrong ls before, got no idea

sorry for wasting time...

the problem with the /etc/config/wireless i haven't solved yet however

cheers tony

**Comment by greenbreakfast** [comment]
@tonytee no worries, good to know .hidden files still make it into the filesystem

cheers!

**Comment by tonytee** [comment]
welll... seems i was not completely crazy...

an invisible file in the root of the filesystem (so directly placed in the "files" directory) does not get into the build...
which is too bad because i need to put the directory /.git/ in the root of the filesystem

my clunky workaround for now is, i named the .git directory INVISIBLEGIT and test for it on first boot and rename 

invisible files inside directories like root and etc DO get processed
my guess this is not a wrapper issue perse, it probably also exists in the original imagebuilder

this therefor just for your entertainment, i wont re-open

**Comment by greenbreakfast** [comment]
@tonytee thanks for the update, that's good to know. I've updated the readme to mention this!
