### ISSUE TITLE
custom /etc/config/wireless file is not honoured after first boot

### ISSUE THREAD

**Issue by tonytee** [OnionIoT/openwrt-imagebuilder-wrapper#18]
when i put a <buildroot>/files/etc/config/wireless file in additions it does show up in the build_dir in the right place with the right contents.

however, after startup of the freshly flashed omega the file /etc/config/wireless seems to be the generic one, with the MySSID and MyKey placeholders in it.

edit: same happens to /etc/config/system it seems

Is this to be expected?

**Comment by greenbreakfast** [comment]
@tonytee actually you've run into a special case! 

We use [UCI defaults](https://openwrt.org/docs/guide-developer/uci-defaults) to preconfigure the `wireless` and `system` configs as part of the `omega2-base` package:
- https://github.com/OnionIoT/OpenWRT-Packages/blob/openwrt-22.03/omega2-base/files/etc/uci-defaults/15_network
- https://github.com/OnionIoT/OpenWRT-Packages/blob/openwrt-22.03/omega2-base/files/etc/uci-defaults/13_hostname

These UCI default scripts probably **overwrite** your `/etc/config/wireless` and `/etc/config/system` files.

The additions as you're doing them will work for files not modified by any UCI defaults.

To get around this issue, you can make a new UCI defaults script to make the changes you need. 

Use the additions feature to place it in `/etc/uci-defaults/` and, to make sure it runs after the existing UCI default scripts, name it with a high leading number, like `99_tonytee` - they run based on alphabetical order.


Let me know how it goes!

**Comment by tonytee** [comment]
Well @greenbreakfast, thanks for your quick reply, on a saturday even...

And also for a great solution, it works like a charm
It was easy to take your scripts as an example and use them as a base for the 99_i_know_it_all_better_script

In fact, this new inmagebuilder-wrapper approach is an absolute winner.

Took me about a day or so to get our product in there completely, and end up with an all-in-one firmware that doesn't even need tweaking after flashing. 

I think i have to refine it just a little more, but we're nearly there, no big hurdles to jump left at all, i'm a  total fan...
Thanks a lot for the hard work on this solution and for the help in the last couple of days...

Have a good weekend
Tony
