### ISSUE TITLE
Upgrade to using OpenWRT 22.03.3 Image Builder

### ISSUE THREAD

**Issue by greenbreakfast** [OnionIoT/openwrt-imagebuilder-wrapper#3]
## Motivation

Move the Omega2 firmware to be based on the latest OpenWRT release

## Description

Update this repo and [OnionIoT/openwrt-sdk-wrapper](https://github.com/OnionIoT/openwrt-sdk-wrapper/) to use the OpenWRT 22.03.3 release versions of the SDK and image builder.

For any device-side things that need to change, please update the [openwrt-22.03 branch in OnionIoT/openwrt-packages](https://github.com/OnionIoT/OpenWRT-Packages/tree/openwrt-22.03).
The omega2-base PKG_VERSION number will definitely need to be updated.

## Resources

https://downloads.openwrt.org/releases/22.03.3/targets/ramips/mt76x8/

**Comment by greenbreakfast** [comment]
@jempatel I've merged in the two PRs related to this issue - https://github.com/OnionIoT/openwrt-imagebuilder-wrapper/pull/5 and https://github.com/OnionIoT/openwrt-sdk-wrapper/pull/3 - and made updates so CD can pick this up and build it (https://github.com/OnionIoT/openwrt-sdk-wrapper/commit/f587aae5ed1c4659be5094feaefd0151b284414d, https://github.com/OnionIoT/OpenWRT-Packages/commit/1821fe407718270cee56918abc850896cc95ff6f).

Newly built `onion_omega2p-22.03.3-20230414.bin` fw is available at http://repo.onioniot.com/omega2/images/openwrt-22.03/.

Can you please try it out and make sure everything still works as expected? 
Please make sure all the hardware interfaces from the [technical doc](https://github.com/OnionIoT/OpenWRT-Packages/blob/openwrt-22.03/technical-doc.md) work too.

**Comment by jempatel** [comment]
> @jempatel I've merged in the two PRs related to this issue - #5 and [OnionIoT/openwrt-sdk-wrapper#3](https://github.com/OnionIoT/openwrt-sdk-wrapper/pull/3) - and made updates so CD can pick this up and build it ([OnionIoT/openwrt-sdk-wrapper@f587aae](https://github.com/OnionIoT/openwrt-sdk-wrapper/commit/f587aae5ed1c4659be5094feaefd0151b284414d), [OnionIoT/OpenWRT-Packages@1821fe4](https://github.com/OnionIoT/OpenWRT-Packages/commit/1821fe407718270cee56918abc850896cc95ff6f)).
> 
> Newly built `onion_omega2p-22.03.3-20230414.bin` fw is available at http://repo.onioniot.com/omega2/images/openwrt-22.03/.
> 
> Can you please try it out and make sure everything still works as expected? Please make sure all the hardware interfaces from the [technical doc](https://github.com/OnionIoT/OpenWRT-Packages/blob/openwrt-22.03/technical-doc.md) work too.

All below points are tested and verified on omega2p and everything works fine

- USB serial connection
- SSH Login with default username pass
- Ethernet WAN over DHCP
- Etherlan LAN with DHCP Server
- Wireless Client as WAN
- Wireless AP 
- I2C
- SPI
- SD Card
- USB Storage Pen drive

**Comment by greenbreakfast** [comment]
Thanks @jempatel, safe to say this is complete - closing this issue.

Out of curiosity, for the SPI interface check, did you just verify `/dev/spidev0.1` exists or did you try sending any data through the SPI intf?
